---
- name: Install requirements
  package:
    name: ["openssl"]
    state: present

- include_tasks: ca-generation.yml
  when: cert_create_ca

- name: Create Cert private key
  openssl_privatekey:
    path: "{{ item.private_key_path }}"
    type: "{{ item.type }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ cert_private_key }}"

- name: Create a CSR for the certificate.
  openssl_csr:
    path: "{{ item.path }}"
    privatekey_path: "{{ item.private_key_path }}"
    country_name: "{{ item.country_name }}"
    organization_name: "{{ item.organization_name }}"
    email_address: "{{ item.mail_address }}"
    common_name: "{{ item.common_name }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    subject_alt_name: "{{ item.subject_alt_name }}"
    basic_constraints: "{{ item.basic_constraints }}"
    mode: "{{ item.mode }}"
  with_items: "{{ cert_csr }}"

- name: Create a self-signed certificate(Without our CA)
  openssl_certificate:
    path: "{{ item.path }}"
    privatekey_path: "{{ item.private_key_path }}"
    csr_path: "{{ item.csr_path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    provider: "{{ item.provider }}"
    mode: "{{ item.mode }}"
  with_items: "{{ cert_cert }}"
  when: cert_use_self_signed and not cert_use_ownca

- name: Create a self-signed certificate(Without our CA)
  openssl_certificate:
    path: "{{ item.path }}"
    privatekey_path: "{{ item.private_key_path }}"
    csr_path: "{{ item.csr_path }}"
    ownca_path: "{{ item.ca_path }}"
    ownca_privatekey_path: "{{ item.ca_privatekey_path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    provider: "{{ item.provider }}"
    mode: "{{ item.mode }}"
  with_items: "{{ cert_cert }}"
  when: cert_use_self_signed and cert_use_ownca
