---
- name: Install requirements
  ansible.builtin.package:
    name: ["openssl", "python3-pip", "python3-setuptools", "python3-dev"]
    state: present

- name: Install pip requirements
  ansible.builtin.pip:
    name: ["cryptography"]
    state: present
    executable: "pip3"

- include_tasks: ca-generation.yml
  when: cert_create_ca

- name: Create Cert private key
  ansible.builtin.openssl_privatekey:
    path: "{{ item.private_key_path }}"
    type: "{{ item.type }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ cert_private_key }}"

- name: Create a CSR for the certificate.
  ansible.builtin.openssl_csr:
    path: "{{ item.path }}"
    privatekey_path: "{{ item.private_key_path }}"
    country_name: "{{ item.country_name }}"
    organization_name: "{{ item.organization_name }}"
    email_address: "{{ item.mail_address }}"
    common_name: "{{ item.common_name }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    subject_alt_name: "{{ item.subject_alt_name }}"
    basic_constraints: "{{ item.basic_constraints }}"
    mode: "{{ item.mode }}"
  with_items: "{{ cert_csr }}"

- name: Create a self-signed certificate(Without our CA)
  ansible.builtin.openssl_certificate:
    path: "{{ item.path }}"
    privatekey_path: "{{ item.private_key_path }}"
    csr_path: "{{ item.csr_path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    provider: "{{ item.provider }}"
    mode: "{{ item.mode }}"
  with_items: "{{ cert_cert }}"
  when: cert_use_self_signed and not cert_use_ownca

- name: Create a self-signed certificate(With our CA)
  ansible.builtin.openssl_certificate:
    path: "{{ item.path }}"
    privatekey_path: "{{ item.private_key_path }}"
    csr_path: "{{ item.csr_path }}"
    ownca_path: "{{ item.ca_path }}"
    ownca_privatekey_path: "{{ item.ca_privatekey_path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    provider: "{{ item.provider }}"
    mode: "{{ item.mode }}"
  with_items: "{{ cert_cert }}"
  when: cert_use_self_signed and cert_use_ownca
